<?php $this->layout('view::layout/guest', ['title' => "Login"]); ?>

<div class="min-h-screen px-2 py-4 mx-auto max-w-7xl">
    <form method="post" action="/login" hx-post="/login" hx-target="#error_container" hx-swap="innerHTML"
        hx-on:htmx:before-request="document.querySelector('#error_container').innerHTML=''"
        hx-on:htmx:after-request="document.querySelector('#user_password').value=''"
        class="max-w-[45rem] mx-auto flex flex-col gap-2 mt-12 px-2">
        <h1 class="text-3xl font-bold text-center">Login</h1>

        <!-- <x-error /> -->
        <div id="error_container" class="text-sm text-red-700">
            <?php foreach ($errors as $error): ?>
                <p><?= $this->e($error) ?></p>
            <?php endforeach; ?>
        </div>

        <!-- <x-input id="user_login" label="Usuáruio" placeholder="username"> -->
        <?= component('input', ['id' => 'user_login', 'label' => 'Usuário']) ?>

        <!-- <x-input id="first_name" label="First Name"> -->
        <?= component('password-input', ['id' => 'user_password', 'label' => 'Senha']) ?>

        <!-- <x-primary-button>Login</x-primary-button> -->
        <?= component('primary-button', ['slot' => 'Login'], [
            'class' => 'w-min ml-auto'
        ]) ?>
    </form>
</div>