<?php if (isset($href)): ?>
    <a <?= $attributes->merge([
        'class' => "cursor-pointer text-red-500 border border-red-800 hover:border-red-900 focus:outline-none focus:ring-4 focus:ring-gray-300 font-medium rounded-lg text-sm px-5 py-2.5",
        'href' => $href
    ]) ?>>
        <?= $slot ?>
    </a>
<?php else: ?>
    <button <?= $attributes->merge([
        "class" => "cursor-pointer text-red-800 border border-red-800 hover:border-red-900 focus:outline-none focus:ring-4 focus:ring-gray-300 font-medium rounded-lg text-sm px-5 py-2.5",
    ]) ?>>
        <?= $slot ?>
    </button>
<?php endif; ?>