<div class="flex flex-col items-center min-h-full p-2 border-l border-l-neutral-100 bg-neutral-50">
    <div class="flex flex-col items-end w-12 h-12" x-data="{ open: false }">
        <img src="/assets/user.svg" alt="User Profile" class="cursor-pointer" @click="open = !open">
        <ul class="shadow *:px-2 py-1.5 min-w-32 bg-white z-50" x-show="open" @click.outside="open = false">
            <li class="text-lg font-medium">Usuário</li>
            <hr class="h-px my-2 bg-gray-200 border-0">
            <li class="hover:bg-neutral-50">
                <button hx-get="/logout" class="w-full text-red-700 cursor-pointer text-start">Sair</button>
            </li>
        </ul>
    </div>
    <hr class="w-full h-px my-2 bg-gray-300 border-0">
    <a hx-boost="true" href="/anoes" class="p-1">
        <div class="w-6 h-6">
            <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 576 512">
                <!--!Font Awesome Free 6.7.2 by @fontawesome - https://fontawesome.com License - https://fontawesome.com/license/free Copyright 2025 Fonticons, Inc.-->
                <path
                    d="M575.8 255.5c0 18-15 32.1-32 32.1h-32l.7 160.2c0 2.7-.2 5.4-.5 8.1v16.2c0 22.1-17.9 40-40 40h-16c-1.1 0-2.2 0-3.3-.1-1.4.1-2.8.1-4.2.1L416 512h-24c-22.1 0-40-17.9-40-40v-88c0-17.7-14.3-32-32-32h-64c-17.7 0-32 14.3-32 32v88c0 22.1-17.9 40-40 40h-55.9c-1.5 0-3-.1-4.5-.2-1.2.1-2.4.2-3.6.2h-16c-22.1 0-40-17.9-40-40V360c0-.9 0-1.9.1-2.8v-69.7h-32c-18 0-32-14-32-32.1 0-9 3-17 10-24L266.4 8c7-7 15-8 22-8s15 2 21 7l255.4 224.5c8 7 12 15 11 24z" />
            </svg>
        </div>
    </a>
</div>