<?php $this->layout('view::layout/app', ['title' => "Gerenciar anão"]); ?>

<div class="min-h-screen px-2 py-4 mx-auto max-w-7xl block">
    <div id="container" class="">
        <?= $this->fetch('view::partials/anao/view') ?>
    </div>

    <?= component('primary-button', [
        'slot' => "EDIT",
    ], [
        'hx-get' => '/anao/edit',
        'hx-trigger' => 'click',
        'hx-target' => '#container',
        'hx-swap' => 'innerHTML'
    ]) ?>
</div>