<?php $this->layout('view::layout/app', ['title' => "Gerenciar anão"]); ?>

<div class="min-h-screen px-2 py-4 mx-auto max-w-7xl">
    <div id="container"></div>

    <?= component('primary-button', [
        'slot' => "SHOW",
    ], [
        'hx-get' => '/anao/show',
        'hx-trigger' => 'load, click',
        'hx-target' => '#container',
        'hx-swap' => 'innerHTML'
    ]) ?>
    <?= component('primary-button', [
        'slot' => "EDIT",
    ], [
        'hx-get' => '/anao/edit',
        'hx-trigger' => 'click',
        'hx-target' => '#container',
        'hx-swap' => 'innerHTML'
    ]) ?>
</div>