<?php $this->layout('view::layout/app', ['title' => "Cadastrar Anão"]); ?>

<div class="flex flex-col px-2 py-4 mx-auto max-w-7xl">
    <form action="/anao/store" method="POST" hx-post="/anao/store" hx-target="#error_container" hx-swap="innerHTML">
        <div class="flex items-end">
            <h1 class="flex-1 my-2 text-3xl font-bold">Cadastrar Anão</h1>
        </div>
        <div id="error_container" class="text-sm text-red-700">
            <?php foreach ($errors as $error): ?>
                <p><?= $this->e($error) ?></p>
            <?php endforeach; ?>
        </div>
        <div class="flex flex-col gap-2">
            <!-- <x-input id="name" label="Nome" :disabled="disabled" /> -->
            <?= component(
                name: 'input',
                props: ['id' => 'name', 'label' => "Nome"],
                attributes: ['max' => '255', 'required' => true],
            ) ?>
            <?= component(
                name: 'input',
                props: ['id' => 'age', 'label' => "Idade"],
                attributes: ['type' => 'number', 'required' => true],
            ) ?>
            <div x-data="{ selected: 4 }">
                <label for="race" class="block font-medium text-gray-900">Etnia</label>
                <select name="race" id="race" :disabled="disabled" x-model="selected"
                    class="disabled:bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5">
                    <option value="4">Outro</option>
                    <option value="0">Negro</option>
                    <option value="1">Branco</option>
                    <option value="2">Pardo</option>
                    <option value="3">Asiático</option>
                </select>
            </div>
            <?= component(
                name: 'input',
                props: ['id' => 'height', 'label' => "Altura (metros)"],
                attributes: ['type' => 'number', 'step' => '0.01', 'min' => '0', 'required' => 'true'],
            ) ?>
            <?= component('primary-button', ['slot' => 'Cadastrar'], [
                'class' => 'w-min ml-auto',
            ]) ?>
        </div>
    </form>
</div>