<?php $this->layout('view::layout/app', ['title' => "Anão " . $anao->id ?? -1]); ?>

<div class="flex flex-col px-2 py-4 mx-auto max-w-7xl">
    <form id="anao_form" action="/anao/update/<?= $anao->id ?? 0 ?>" method="POST" x-data="{ disabled: true }"
        hx-post="/anao/update/<?= $anao->id ?? 0 ?>" hx-target="this" hx-swap="innerHTML" hx-select="#anao_form">
        <div class=" flex gap-1 items-center">
            <h1 class="flex-1 my-2 text-4xl font-bold">Anão #<?= $anao->id ?? 'Desconhecido' ?></h1>
            <?= component(
                name: 'primary-button',
                props: ['slot' => 'Editar'],
                attributes: ['type' => 'button', '@click' => 'disabled = false', 'x-show' => 'disabled'],
            ) ?>
            <?= component(
                name: 'danger-button',
                props: ['slot' => 'Excluir'],
                attributes: [
                    'type' => 'button',
                    'x-show' => 'disabled',
                    'hx-post' => "/anao/destroy/$anao->id",
                    'hx-confirm' => 'Tem certeza que deseja remover permanentemente este Anão?'
                ],
            ) ?>
            <?= component(
                name: 'primary-button',
                props: ['slot' => 'Salvar'],
                attributes: ['x-show' => '!disabled'],
            ) ?>
            <?= component(
                name: 'secondary-button',
                props: ['slot' => 'Cancelar'],
                attributes: [
                    'type' => 'button',
                    'x-show' => '!disabled',
                    'hx-get' => "/anao/$anao->id",
                    "hx-target" => 'closest form',
                    "hx-select" => '#anao_form'
                ],
            ) ?>
        </div>
        <h2 class="mt-2 text-3xl font-medium">Dados</h2>
        <div id="error_container" class="text-sm text-red-700">
            <?php foreach ($errors as $error): ?>
                <p><?= $this->e($error) ?></p>
            <?php endforeach; ?>
        </div>
        <div class="flex flex-col gap-2">
            <!-- <x-input id="name" label="Nome" :disabled="disabled"_/> -->
            <?= component(
                name: 'input',
                props: ['id' => 'name', 'label' => "Nome"],
                attributes: ['max' => '255', ':disabled' => 'disabled', 'value' => $anao->name ?? ''],
            ) ?>
            <?= component(
                name: 'input',
                props: ['id' => 'age', 'label' => "Idade"],
                attributes: ['type' => 'number', ':disabled' => 'disabled', 'value' => $anao->age ?? ''],
            ) ?>
            <div x-data="{ selected: <?= $anao->race ?? 4 ?> }">
                <label for="race" class="block font-medium text-gray-900">Etnia</label>
                <select name="race" id="race" :disabled="disabled" x-model="selected"
                    class="disabled:bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5">
                    <option value="4">Outro</option>
                    <option value="0">Negro</option>
                    <option value="1">Branco</option>
                    <option value="2">Pardo</option>
                    <option value="3">Asiático</option>
                </select>
            </div>
            <?= component(
                name: 'input',
                props: ['id' => 'height', 'label' => "Altura (metros)"],
                attributes: ['type' => 'number', 'step' => '0.01', 'min' => '0', ':disabled' => 'disabled', 'value' => $anao->height ?? ''],
            ) ?>
        </div>
    </form>
    <hr class="h-px my-6 bg-gray-300 border-0" />
    <h2 class="text-3xl font-medium">Parceiros</h2>
    <div class="flex flex-col gap-2">
        <?php foreach ($parceiros as $parceiro): ?>
            <?= $this->fetch('view::partials/parceiro-form', ['parceiro' => $parceiro, 'id_anao' => $anao->id ?? 0]) ?>
        <?php endforeach; ?>
        <?= component('secondary-button', ['slot' => '+ Adicionar Parceiro'], [
            'class' => 'w-fit mx-auto',
            'hx-get' => "/parceiro/create?id_anao=" . $anao->id ?? 0,
            'hx-target' => 'this',
            'hx-swap' => 'beforebegin',
        ]) ?>
    </div>
</div>