<form action="/parceiro/update/<?= $this->e($parceiro->id) ?>" method="POST"
    hx-post="/parceiro/update/<?= $this->e($parceiro->id) ?>" hx-target="this" hx-swap="outerHTML"
    class="flex justify-between p-3 rounded shadow" x-data="{ disabled: <?= $disabled ?? 'true' ?> }">
    <div class="flex flex-col gap-2">
        <?= component('compact-input', [
            'id' => 'name',
            'label' => 'Nome: '
        ], [':disabled' => 'disabled', 'value' => $parceiro->name ?? '']) ?>
        <?= component('compact-input', [
            'id' => 'contact',
            'label' => 'Contato: '
        ], [':disabled' => 'disabled', 'value' => $parceiro->contact ?? '']) ?>
        <div>
            <span class="font-medium">É anão:</span>
            <input type="radio" name="is_anao" id="is_anao_yes" value="1" :disabled="disabled" <?= $parceiro->is_anao ? 'checked' : '' ?>>
            <label for="is_anao_yes">Sim</label>
            <input type="radio" name="is_anao" id="is_anao_no" value="0" :disabled="disabled" <?= $parceiro->is_anao ? '' : 'checked' ?>>
            <label for="is_anao_no">Não</label>
        </div>
    </div>
    <div class="flex flex-col gap-1">
        <?= component('secondary-button', ['slot' => 'Salvar'], ['x-show' => '!disabled']) ?>
        <?= component('secondary-button', ['slot' => 'Cancelar'], ['type' => 'button', 'x-show' => '!disabled', '@click' => 'disabled = true']) ?>
        <?= component('primary-button', ['slot' => 'Editar'], ['type' => 'button', 'x-show' => 'disabled', '@click' => 'disabled = false']) ?>
        <?= component('danger-button', ['slot' => 'Excluir'], [
            'x-show' => 'disabled',
            'hx-post' => "/parceiro/destroy/$parceiro->id",
            'hx-confirm' => 'Tem certeza que deseja remover permanentemente este Parceiro?'
        ]) ?>
    </div>
</form>