<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><?= $this->e($title ?? 'Anões') ?></title>
    <?= vite(['resources/css/app.css', 'resources/js/app.js']) ?>
</head>

<body">
    <div class="flex h-screen overflow-hidden">
        <div class="flex-1 overflow-y-auto">
            <?= $this->section('content') ?>
        </div>
        <?= component('navbar') ?>
    </div>
    </body>

</html>