<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><?= $this->e($title ?? 'Anões') ?></title>
    <!-- <link rel="stylesheet" href="/build/style.css"> -->
    <script type="module" src="http://localhost:5173/@vite/client"></script>
    <script type="module" src="http://localhost:5173/resources/js/app.js"></script>
    <link rel="stylesheet" href="http://localhost:5173/resources/css/app.css">
</head>

<body>
    <?= $this->section('content') ?>
</body>

</html>